version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_financas
    environment:
      POSTGRES_DB: financas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
